DROP TABLE ZAMOWIENIA_PALIWOWE;
DROP TABLE ZAMOWIENIA_SPOZYWCZE;
DROP TABLE KLIENCI;
DROP TABLE PALIWA;
DROP TABLE HISTORIA_CEN_PALIW;
DROP TABLE TYP_PALIWA;
DROP TABLE PRODUKTY_SPOZYWCZE;
DROP TABLE DOSTAWCY_SPOZYWCZY;
DROP TABLE DOSTAWCY_PALIWOWI;
COMMIT;

