
-- on_petrol_delivery
CREATE OR REPLACE TRIGGER ON_PETROL_DELIVERY 
BEFORE INSERT ON ZAMOWIENIA_PALIWOWE 
FOR EACH ROW
DECLARE delivery_present INTEGER;
BEGIN
   SELECT COUNT(*)
    INTO delivery_present
    FROM ZAMOWIENIA_PALIWOWE
    WHERE EXTRACT(YEAR FROM DATA_ZAMOWIENIA) = EXTRACT(YEAR FROM :NEW.DATA_ZAMOWIENIA)
    AND EXTRACT(MONTH FROM DATA_ZAMOWIENIA) = EXTRACT(MONTH FROM :NEW.DATA_ZAMOWIENIA)
    AND EXTRACT(DAY FROM DATA_ZAMOWIENIA) = EXTRACT(DAY FROM :NEW.DATA_ZAMOWIENIA);

    IF delivery_present > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Tego dnia paliwo juz bylo zamawiane');
    END IF;
END;




--on_products_delivery
CREATE OR REPLACE TRIGGER ON_PRODUCTS_DELIVERY 
BEFORE INSERT ON ZAMOWIENIA_SPOZYWCZE 
FOR EACH ROW
DECLARE
    delivery_present INTEGER;
BEGIN
  SELECT COUNT(*)
    INTO delivery_present
    FROM ZAMOWIENIA_SPOZYWCZE
    WHERE EXTRACT(YEAR FROM DATA_ZAMOWIENIA) = EXTRACT(YEAR FROM :NEW.DATA_ZAMOWIENIA)
    AND EXTRACT(MONTH FROM DATA_ZAMOWIENIA) = EXTRACT(MONTH FROM :NEW.DATA_ZAMOWIENIA)
    AND EXTRACT(DAY FROM DATA_ZAMOWIENIA) = EXTRACT(DAY FROM :NEW.DATA_ZAMOWIENIA);

    IF delivery_present > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Tego dnia produkty spozywcze juz bylo zamawiane');
    END IF;
END;