-- instancja: STACJA PALIW
CREATE USER AdministratorOracle IDENTIFIED BY 123;

GRANT ALL PRIVILEGES TO AdministratorOracle;

-- instancja: MYJNIA
CREATE USER Myjnia IDENTIFIED BY 123;

GRANT CREATE SESSION TO Myjnia;
GRANT CREATE TABLE TO Myjnia;
GRANT CREATE PROCEDURE TO Myjnia;
GRANT CREATE SEQUENCE TO Myjnia;
GRANT CREATE VIEW TO Myjnia;
GRANT CREATE TRIGGER TO Myjnia;
GRANT CREATE SYNONYM TO Myjnia;

--GRANT ALL PRIVILEGES TO Myjnia;

ALTER USER Myjnia QUOTA unlimited ON users;

--je¿eli wywali blad ¿e uprawienia nie zostaly przyznane to dobrze
REVOKE SELECT ANY TABLE FROM Myjnia;
REVOKE INSERT ANY TABLE FROM Myjnia;
REVOKE UPDATE ANY TABLE FROM Myjnia;
REVOKE DELETE ANY TABLE FROM Myjnia;

GRANT CREATE DATABASE LINK TO Myjnia;

CREATE PUBLIC DATABASE LINK StacjaPubliczny
CONNECT TO AdministratorOracle IDENTIFIED BY "123"
USING '(DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SID = orcl)
    )
  )';

